### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by athenawisdoms** [johnsmith0031/alpaca_lora_4bit#130]
I get the error `TypeError: object of type 'NoneType' has no len()` when running `finetune.py` using a text file for my dataset. 

This error is raised because `data.val_data` is `None`. Looking into `TrainTxt` class, it notice it does not set `self.val_data` in `TrainTxt.prepare_data`.

Do not know how to fix this myself, hope to get some help!

**Comment by johnsmith0031** [comment]
If not using validation set, you should pass --val_set_size=0
