### ISSUE TITLE
module 'alpaca_lora_4bit.quant_cuda' has no attribute 'vecquant4recons_v2'

### ISSUE THREAD

**Issue by kevkid** [johnsmith0031/alpaca_lora_4bit#147]
Cant seem to run the trainer as in finetune.py Do I need to do something special? Do I need gptq4llama installed?
`module 'alpaca_lora_4bit.quant_cuda' has no attribute 'vecquant4recons_v2'`
I see that inside alpaca_lora_4bit.quant_cuda there are cpp files, how would I use/compile these?

**Comment by johnsmith0031** [comment]
Maybe the cuda kernel is not up to date.
You can uninstall alpaca_lora_4bit first and reinstall it.

**Comment by kevkid** [comment]
> Maybe the cuda kernel is not up to date. You can uninstall alpaca_lora_4bit first and reinstall it.

I uninstalled all packages in the conda environment that is running in WSL, then did `pip install -r requirements.txt` in the repos folder, and I specifically removed wandb. 
I then proceded to install the repo by doing `pip install .`
The only thing that is installed are the requirements of the repo. how can I ensure the cuda kernel is reinstalled (or is it reinstalled via the requirements.txt?)

![image](https://github.com/johnsmith0031/alpaca_lora_4bit/assets/1369930/351f87b6-0ec8-44f0-8a66-782b097eaa64)

**Comment by johnsmith0031** [comment]
Weird. Maybe you should try this:
```
python setup.py install
```
but may conflict with the version that pip installed.

**Comment by kevkid** [comment]
> Weird. Maybe you should try this:
> 
> ```
> python setup.py install
> ```
> 
> but may conflict with the version that pip installed.

Thank you this worked!
