### ISSUE TITLE
docker.io/nvidia/cuda:11.7.0-devel-ubuntu22.04 not available anymore

### ISSUE THREAD

**Issue by kkaarrss** [johnsmith0031/alpaca_lora_4bit#151]
Seems cuda:11.7.0-devel-ubuntu22.04 is not available anymore on docker hub, but 11.7.1 is. I updated my Dockerfile and that seems to work.

**Comment by johnsmith0031** [comment]
Thanks! I've changed 11.7.0 to 11.7.1
