### ISSUE TITLE
Inferencing? 

### ISSUE THREAD

**Issue by Arargd** [johnsmith0031/alpaca_lora_4bit#3]
I'm curious about using this for inferencing on an existing llama 4bit model. Replacing the lora file, and replacing the others and recompiling I have done already. However when attempting to load the lora. I get (short snippet of the full error)

```
  File "C:\Users\Arargd\miniconda3\envs\textgen\lib\site-packages\peft\tuners\lora.py", line 191, in _find_and_replace
    self._replace_module(parent, target_name, new_module, target)
UnboundLocalError: local variable 'new_module' referenced before assignment
```
Which is the same error you get if you try to load onto a 4bit model normally. 

Am I missing something, or what do I need to do to get inferencing working on an existing 4bit model?

**Comment by johnsmith0031** [comment]
Which version of files are you using? I've done several updates on them.

And are those 2 parts replaced?
![image](https://user-images.githubusercontent.com/16870323/226777070-0c9b8d85-4512-40ad-9a60-cca6b09ca139.png)
![image](https://user-images.githubusercontent.com/16870323/226777120-a38a39f9-e41a-4a14-8e22-96ebce44597c.png)

You can also try load the model using load_llama_model_4bit_low_ram.

And also I'll upload an inference example / training example later.

**Comment by Arargd** [comment]
Using your examples I was able to get it to run!
