### ISSUE TITLE
Can't compile GPTQ fork

### ISSUE THREAD

**Issue by brandonj60** [johnsmith0031/alpaca_lora_4bit#31]
```
site-packages\torch\include\pybind11\cast.h(624): error: too few arguments for template template parameter "Tuple"
                detected during instantiation of class "pybind11::detail::tuple_caster<Tuple, Ts...> [with Tuple=std::pair, Ts=<T1, T2>]"
      (721): here

site-packages\torch\include\pybind11\cast.h(717): error: too few arguments for template template parameter "Tuple"
                detected during instantiation of class "pybind11::detail::tuple_caster<Tuple, Ts...> [with Tuple=std::pair, Ts=<T1, T2>]"
      (721): here

      2 errors detected in the compilation of "src/gptq_llama/quant_cuda/quant_cuda_kernel.cu".
      quant_cuda_kernel.cu
      error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.6\\bin\\nvcc.exe' failed with exit code 1
```

Is there a precompiled whl out there for the quant_cuda files from the lora_4bit fork? I've never been able to compile these locally for some reason.

**Comment by johnsmith0031** [comment]
Which version of pytorch do you use?
Currently early version of pytorch is not tested, and upgrading pytorch to 2.0.0 is recommended.

**Comment by brandonj60** [comment]
I'm on 2.0.0, but also tried 1.3.1. I've tried CUDA 11.6 and 11.8, multiple versions of C++ Build Tools (2019 and 2023), and have never had any luck.

**Comment by johnsmith0031** [comment]
Updated cuda kernel in GPTQ fork and you can have another try

**Comment by brandonj60** [comment]
Nah, same result after pulling.

**Comment by brandonj60** [comment]
Ok, I finally got it to run. I can't tell if the compiler was picking up a pytorch version different from the one my conda environment was using, or if there was a problem with CUDA 11.6 (or both). Regardless, cleaning up a bunch of extraneous Pytorch installs and upgrading to CUDA 11.8 solved the issue.

**Comment by tensiondriven** [comment]
@brandonj60 Can you provide the command line you used and any other relevant info, for the benefit of others?
