### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by ehartford** [johnsmith0031/alpaca_lora_4bit#4]
Can you please provide step by step instructions?  
the readme doesn't give me enough information for me to set it up and run inference on my computer.

**Comment by johnsmith0031** [comment]
I'll write a more detailed version of them.
I'll upload an inference example / training example later.

**Comment by s4rduk4r** [comment]
First of all want to say my thanks for sharing your code - its great. I've took a liberty to write a short guide on how to start the model with your code under Windows 10 WSL. Hope it helps - https://github.com/s4rduk4r/alpaca_lora_4bit_readme/blob/main/README.md

**Comment by johnsmith0031** [comment]
> First of all want to say my thanks for sharing your code - its great. I've took a liberty to write a short guide on how to start the model with your code under Windows 10 WSL. Hope it helps - https://github.com/s4rduk4r/alpaca_lora_4bit_readme/blob/main/README.md

Oh Thank you!

**Comment by ehartford** [comment]
Thank you @s4rduk4r
