### ISSUE TITLE
peft.tuners.lora missing Linear4bitLt?

### ISSUE THREAD

**Issue by SpaceCowboy850** [johnsmith0031/alpaca_lora_4bit#44]
I'm following these instructions:
https://github.com/s4rduk4r/alpaca_lora_4bit_readme/blob/main/README.md

I get the following error attempting to spin up the text-generation-webui
  File "D:\github\alpaca_lora_4bit\text-generation-webui\custom_monkey_patch.py", line 6, in <module>
    from peft.tuners.lora import Linear4bitLt
ImportError: cannot import name 'Linear4bitLt' from 'peft.tuners.lora' (C:\Users\...\Anaconda3\envs\alpaca\lib\site-packages\peft\tuners\lora.py)

Looking at the peft github, I don't see anything about a Linear4bitLt...is this a custom branch I need to pull of PEFT?

I can run python inference.py and it runs fine, but the monkey patch seems to not work for text-generation-webui

**Comment by brandonj60** [comment]
The requirements.txt shows the dependency needed for Peft.
git+https://github.com/sterlind/peft.git

**Comment by SpaceCowboy850** [comment]
ah, I think I missed the "sterlind" part when I was going through it - thanks
