### ISSUE TITLE
Will the Triton branch of GPTQ with parameters --true-sequential --act-order --groupsize 128 be supported?

### ISSUE THREAD

**Issue by luxtiasco** [johnsmith0031/alpaca_lora_4bit#57]
These parameters give the best quantization results currently, but I'm not sure if they are compatible with the current 4-bit LoRA.

**Comment by johnrobinsn** [comment]
@luxtiasco do you have a set of parameters that works?... I'm struggling getting a quantized model that I've created working.    My last failed attempts used all three params... --true-sequential, --act-order and --groupsize 128
... I'll try removing the first two to see if I can get something to train.

**Comment by johnsmith0031** [comment]
Now triton backend support v2 model with --true-sequential, --act-order.
Will add cuda backend support in the future.

**Comment by luxtiasco** [comment]
I see that the cuda branch is not stable, and even behaves differently from triton.
What version of gptq-llama is supported by alpaca_lora_4bit now?

**Comment by Ph0rk0z** [comment]
I thought cuda supported --true-sequential and --act-order.. just not with group size.

This is the gptq that is supposed to be used: https://github.com/sterlind/GPTQ-for-LLaMa/tree/lora_4bit

**Comment by johnsmith0031** [comment]
Yes I think add g_idx passing into cuda kernel would solve the problem

**Comment by luxtiasco** [comment]
> Yes I think add g_idx passing into cuda kernel would solve the problem

However I find it behaves differently on triton and cuda branch. The current version of cuda branch didn't work as expected. Only triton branch works well, and it seems that qwopqwop200 will work mainly on this branch.

Either to use a cuda branch with no act-order and groupsize together, or to adapt the triton branch.

See https://github.com/qwopqwop200/GPTQ-for-LLaMa/issues/128

**Comment by johnsmith0031** [comment]
Thanks I'll look into it
