### ISSUE TITLE
What about GPTQ v2 format without groupsize?

### ISSUE THREAD

**Issue by Ph0rk0z** [johnsmith0031/alpaca_lora_4bit#65]
I have tried to get things to load for GPTQv2 models that do not use groupsize. Appears it is impossible because groupsize is used to switch between V1 and V2.

**Comment by johnsmith0031** [comment]
updated cuda implementation to support g_idx. I think it'll work now.

**Comment by Ph0rk0z** [comment]
Working great now that I updated the cuda kernel too :)

Thank you!
