### ISSUE TITLE
Automatic download of llama-7b

### ISSUE THREAD

**Issue by neuhaus** [johnsmith0031/alpaca_lora_4bit#67]
Hi, thanks for providing this.

running

    DOCCKER_BUILDKIT=1 docker build -t alpaca_lora_4bit . # build step can take 12 min

automatically downloads the llama-7b-hf-int4 weights from Huggingface. I plan to use a larger model anyway, is there a way to not download the weights automatically and perhaps point it to a different location where the files already reside? Thanks!

**Comment by johnsmith0031** [comment]
Edit line 26 and line 74 before installing. Change the model you want to use.
RUN wget --progress=bar:force:noscroll https://huggingface.co/decapoda-research/llama-7b-hf-int4/resolve/main/llama-7b-4bit.pt
RUN sed -i 's/llama-13b-4bit/llama-7b-4bit/g' text-generation-webui/custom_monkey_patch.py && sed -i 's/alpaca13b_lora/alpaca7b_lora/g' text-generation-webui/custom_monkey_patch.py
